### ISSUE TITLE
Configuration file should be validated about including unknown field

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1041]
**What would you like to be added**:
Even if an unexpected field defined, no error and alert given.
```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  foo: bar
```

It should be checked before starting deployment and failed if any unknown fields found.

**Why is this needed**:
