### ISSUE TITLE
Unable to rollback during performing ADA

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1134]
**What happened**:
Pushing the `Cancel` button then gets stuck for a while. After that, the rollback stage ends with failure leaving this log:

```
[2020-11-24 10:30:13 +09:00]
Preparing deploy source at running commit (ae32a73ec9b24470e83b9ec8d263de6936ca34d6)
[2020-11-24 10:30:13 +09:00]
Failed to prepare running deploy source data (failed to fetch: context canceled)
```

![image](https://user-images.githubusercontent.com/19730728/100035173-e46c0080-2e40-11eb-81ce-c4e5eda81540.png)

**What you expected to happen**:

**How to reproduce it**:
Prepare the pipeline with ANALYSIS stage:

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 20%
          createService: true
      - name: ANALYSIS
        with:
          duration: 20m
          metrics:
            # Error rate
            - provider: prometheus-dev
              interval: 5m
              failureLimit: 1
              expected:
                max: 0
              query: |
                rate(http_requests_total{status=~"5.*", job="podinfo-canary"}[5m])
                /
                rate(http_requests_total{job="podinfo-canary"}[5m])
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
```

Do cancel when performing the ANALYSIS stage.

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:
