### ISSUE TITLE
In `WAIT` stage in KubernetesApp, do not wait for more than 10 seconds.

### ISSUE THREAD

**Issue by ShotaKitazawa** [pipe-cd/pipe#1225]
**What happened**:
In `WAIT` stage in KubernetesApp, do not wait for more than 10 seconds.

**What you expected to happen**:

wait time specified to `duration` key

**How to reproduce it**:

use bellow `.pipe.yaml`

```
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: WAIT
        with:
          duration: 60s
```

**Environment**:
- `piped` version: v0.9.0
- `control-plane` version: v0.9.0
- Others: already created Pull Request: #1226
