### ISSUE TITLE
Change "ImageWatcher" config under .pipe/ to "ImageWatcherTargets"

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1338]
**What would you like to be added**:
- Some people can confuse because there is the `imageWatcher` field in the Piped config. So it would be nice if we can clearly distinguish them by changing the name.
- Currently multiple files are allowed, so we can only configure settings related to the target. (Common repository settings may be duplicated because of multiple files)

Current:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: ImageWatcher
spec:
  targets:
    - image: gcr.io/pipecd/foo
      provider: my-gcr
      filePath: foo/deployment.yaml
      field: $.spec.template.spec.containers[0].image
```

Ideal:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: ImageWatcherTargets
spec:
  - image: gcr.io/pipecd/foo
    provider: my-gcr
    filePath: foo/deployment.yaml
    field: $.spec.template.spec.containers[0].image
```

**Why is this needed**:
