### ISSUE TITLE
Redesign ImageWatcher configuration fields

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1363]
**What would you like to be added**:
Currently, Image watcher can replace only the image string formatted like `repoName:tag`. (e.g. gcr.io/pipecd/helloworld:1.0.0).

We definitely should make it replaceable even if the tag definition is independent like Kustomize and Helm.

kustomization.yaml
```yaml
images:
- name: gcr.io/pipecd/helloworld
  newTag: v0.1.0-73-ge191187
```

.pipe.yaml
```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    helmChart:
      repository: foo
      name: bar
      version: v0.1.0
```

**Why is this needed**:

**Comment by nakabonne** [comment]
I found another problem with the current design. Only one field can be updated per image. Based on these problems, I propose a new `ImageWatcher` configuration fields.

@nghialv @khanhtc1202 It would be great if you give me any feedback!

**Comment by nakabonne** [comment]
I found another problem with the current design. Only one field can be updated per image. Based on these problems, I propose a new `ImageWatcher` configuration fields.

Current design:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: ImageWatcher
spec:
  targets:
    - image: pipecd/foo
      provider: my-dockerhub
      filePath: foo/deployment.yaml
      imageField: $.spec.template.spec.containers[0].image
```

The design I propose:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: ImageWatcher
spec:
  images:
    - name: pipecd/foo
      provider: my-dockerhub
      rewriteTargets:
        - filePath: dev/foo/deployment.yaml
          field: $.spec.template.spec.containers[0].image
        - filePath: stg/foo/kustomization.yaml
          field: $.spec.template.spec.containers[0].image

    - name: gcr.io/pipecd/bar
      provider: my-gcr
      rewriteTargets:
        - filePath: bar/deployment.yaml
          field: $.images[0].newTag
          onlyTag: true
```

If the only tag should be overwritten, just set `onlyTag` to true.

@nghialv @khanhtc1202 It would be great if you give me any feedback!
