### ISSUE TITLE
Enable that Image watcher watches Helm repo

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1370]
**What would you like to be added**:
No longer "Image" watcher, but most Helm users should want to automatically update the following `version` field. 

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    helmChart:
      repository: foo
      name: bar
      version: v0.1.0
```

For that, the `FAKE` image provider is available. However, it could be tough to extract the new version and give it to `pipectl` in the CI workflow.

It would be nice if we could support `HELM` image provider, or something else options.

**Why is this needed**:
