### ISSUE TITLE
Support EventWatcher instead of ImageWatcher

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1381]
**What would you like to be added**:
Stop making ImageWatcher that is still incubating feature. Instead, we just settled on providing the `EventWatcher` feature that is similar to the `FAKE` image provider we originally attempted to support, and a higher-level concept.

**Why is this needed**:
We found no longer needed to watch container registries. Just need the ability to update when the specific event occurred.

First of all we define event-watcher.yaml under the `.pipe/` directory.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: EventWatcher
spec:
  events:
    # For image watcher until now
    - name: app1-image-push # must be unique
      replacements:
        - file: dev/app1/deployment.yaml
          yamlField: $.spec.template.spec.containers[0].image
        - file: stg/app1/deployment.json
          jsonField: $.spec.template.spec.containers[0].image
    # For helm remote chart
    - name: app2-helm-release
      replacements:
        - file: app2/.pipe.yaml
          yamlField: $.spec.input.helmChart.version
```

Then at arbitrary timing, users perform this command to push the event on the CI system. Suppose you want to trigger a Deployment after pushing container image. You can trigger with:
```yaml
pipectl event register \
    --address=CONTROL_PLANE_API_ADDRESS \
    --api-key=API_KEY \
    --name=example-image-pushed \
    --data=gcr.io/pipecd/example:v0.1.0
```

For those who want to deploy after helm release:
```
pipectl event register \
    --address=CONTROL_PLANE_API_ADDRESS \
    --api-key=API_KEY \
    --name=app2-helm-release \
    --data=v0.1.0
```

Needed model is something like that:

```proto
message Event {
    // The generated unique identifier.
    string id = 1 [(validate.rules).string.min_len = 1];
    // The event name.
    string name = 2 [(validate.rules).string.min_len = 1];
    string data = 3 [(validate.rules).string.min_len = 1];
    // The ID of the project this event belongs to.
    string project_id = 4 [(validate.rules).string.min_len = 1];

    // Unix time when the image metadata was created.
    int64 created_at = 14 [(validate.rules).int64.gt = 0];
    // Unix time of the last time when the image metadata is updated.
    int64 updated_at = 15 [(validate.rules).int64.gt = 0];
}
```

Made from the discussion on https://github.com/pipe-cd/pipe/issues/1363

### What we actually need:

- [x] New pipectl sub-command to send an Event to the server by @nghialv 
- [x] gRPC API to store the the new Event by @nghialv 
- [x] Update configurations (the image watcher config compatible with the event watcher config) by @nakabonne 
- [x] Piped API to give back the latest event @nakabonne 
- [x] Event watcher implementation to replace the specified field with the value. by @nakabonne 
- [ ] Update documentation by @nakabonne
