### ISSUE TITLE
pipectl: every command fails

### ISSUE THREAD

**Issue by m-ronchi** [pipe-cd/pipe#1700]
**What happened**: I am trying to use pipectl but it always fail with `Error: failed to initialize client: context deadline exceeded`

**What you expected to happen**: either the command succeeds, or I get a better error message

**How to reproduce it**:
none of the pipectl invocations I tried succeeded:
- `./pipectl_v0.9.7_darwin_amd64 event register --address ***** --api-key ***** --name fake --data fake`
- `docker run gcr.io/pipecd/pipectl:v0.9.7 application list --address ***** --api-key ***** --app-kind KUBERNETES`

I tried both the public address of pipecd (as defined in the ingress) and `localhost:8080` / `host.docker.internal:8080` with `kubectl -n pipecd port-forward svc/pipecd 8080` on my machine.

the port-forward logs `Handling connection for 8080` 3 times for each invocation.
it always fails after 5 seconds `time ./pipectl.....` -> `0,02s user 0,01s system 0% cpu 5,023 total`

I can access the web interface, add applications and deploy them fine

**Environment**:
- `piped` version: 0.9.7
- `control-plane` version: 0.9.7
- Others: pipectl 0.9.7 (both docker and osx binary), osx 10.15.4

**Comment by nghialv** [comment]
@m-ronchi Thanks for your report.

By default `pipectl` connects to the control plane with secure transport. If your control-plane is not configuring TLS so please use the following `insecure` flag to run `pipectl`.

```
pipectl --address *** ... --insecure=true
```

**Comment by m-ronchi** [comment]
`--insecure=true` worked under port-forward, but not using the public address.

**Comment by nghialv** [comment]
@m-ronchi Thanks for your reply. Are you using a normal TLS certificate or using a self-signed one for your public address?

**Comment by m-ronchi** [comment]
We are using a normal certificate generated with cert-manager and we expose the service using the ingress-nginx.
Moreover we had to set our own ingress configuration due to the helm one not working.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pipecd
  annotations:
    cert-manager.io/cluster-issuer: “tls-issuer”
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - **hostname**
      secretName: tls-secret
  rules:
    - host: **hostname**
      http:
        paths:
          - path: /hook
            backend:
              serviceName: pipecd
              servicePort: 8080
          - path: /pipe.api.service.pipedservice.PipedService/*
            backend:
              serviceName: pipecd
              servicePort: 8080
          - path: /pipe.api.service.apiservice.APIService/*
            backend:
              serviceName: pipecd
              servicePort: 8080
          - path: /
            backend:
              serviceName: pipecd
              servicePort: 8080
```
