### ISSUE TITLE
Make Role rules changeable

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1828]
**What would you like to be added**:
Currently, the rules are fixed as below. Better make it possible to change them with some kind of ways.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "piped.fullname" . }}
  labels:
    {{- include "piped.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

**Why is this needed**:
