### ISSUE TITLE
Namespaced Role cannot list resources at the cluster scope

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#1833]
**What would you like to be added**:
Piped with namespace Role couldn't access cluster scope resources.

```
E0407 05:19:22.527348       1 reflector.go:178] external/io_k8s_client_go/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: configmaps is forbidden: User "system:serviceaccount:default:piped-namespaced" cannot list resource "configmaps" in API group "" at the cluster scope
```
```
E0408 06:23:04.021055       1 reflector.go:178] external/io_k8s_client_go/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: serviceaccounts is forbidden: User "system:serviceaccount:default:piped-namespaced" cannot list resource "serviceaccounts" in API group "" at the cluster scope
```

It requires around here:
https://github.com/pipe-cd/pipe/blob/686aea205b7c278e86da409e972898bdc038dcef/pkg/app/piped/livestatestore/kubernetes/reflector.go#L199-L216

Ref: https://github.com/pipe-cd/pipe/pull/1830#issuecomment-814561762
**Why is this needed**:

**Comment by nakabonne** [comment]
Even though `appStateInformer` is set, it still happened. Apparently, seems like it doesn't detect the given cloud provider `k8s-dev` well.

```yaml
      cloudProviders:
        - name: k8s-dev
          type: KUBERNETES
          config:
            masterURL: x.x.x.x:443
            appStateInformer:
              namespace: default
```

**Comment by nakabonne** [comment]
All of them are caused by the default cloud provider. Leverage `enableDefaultKubernetesCloudProvider` and `appStateInformer` then we can start Piped with no pain.

```yaml
args:
  enableDefaultKubernetesCloudProvider: false

config:
  data: |
    apiVersion: pipecd.dev/v1beta1
    kind: Piped
    spec:
      cloudProviders:
        - name: my-kubernetes
          type: KUBERNETES
          config:
            appStateInformer:
              namespace: debug
```
