### ISSUE TITLE
Drift detector is showing the diff on ENV value that consumes a Secret key

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#2035]
**What happened**:

```
apiVersion: v1
kind: Pod
  name: secret-env-pod
spec:
  containers:
  - env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: mysecret
```

<img width="604" alt="Screen Shot 2021-06-03 at 11 15 18" src="https://user-images.githubusercontent.com/1751755/120575996-03d18f00-c45d-11eb-8048-b1fc76a0921c.png">

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:
