### ISSUE TITLE
Empower EventWatcher to replace a YAML file that holds separators

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2212]
**What would you like to be added**:
It's not uncommon that you want to replace YAML files that are already merged with `---`, the end of directives marker.

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: foo
        image: foo:v0.8.0

---
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: bar
        image: bar:v0.8.0
```

In above example, `$.spec.template.spec.containers[0].image` exists in both docs but we (in some case) only want to update the second doc.

**Why is this needed**:

**Comment by khanhtc1202** [comment]
https://github.com/pipe-cd/pipe/blob/master/pkg/yamlprocessor/yamlprocessor.go#L70-L73

If `goccy/go-yaml` doesn't support, we can just accept `$[2].foo` and split the file by `---` before using the rest of the path here 🤔 
But I don't like this workaround 😂

**Comment by nakabonne** [comment]
hmm, `$[2].foo` acutally means like:
```yaml
- a
- b
- 
  c: 
    foo: # here
```
