### ISSUE TITLE
Event watcher can't update YAML files including templating syntax

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2341]
**What would you like to be added**:
Let's say you update a YAML file like below by Event watcher

```yaml
apiVersion: pipecd.dev/v1beta1
kind: LambdaFunction
spec:
  image: foo
  environments:
    FOO: {{ .encryptedSecrets.foo }}
```

Event watcher never updates because the file includes `{{}}`.

```
failed to commit outdated files	{"error": "failed to get value at $.spec.image in /tmp/event-watcher621282109/repo524333230/tmp-repo/services/foo/bar/function.yaml: [6:11] unexpected mapping key\n       3 | spec:\n       4 |   image: foo\n       5 |   environments:\n    >  6 |     FOO: {{ .encryptedSecrets.foo }}\n                     ^"}
```

It's common to have a templating syntax for [Encrypted secret](https://pipecd.dev/docs/user-guide/secret-management/) so it should be handled as soon as possible.

**Why is this needed**:
