### ISSUE TITLE
Add ability to notify WAITING_APPROVAL event to external services like Slack

### ISSUE THREAD

**Issue by nghialv** [pipe-cd/pipe#2342]
**What would you like to be added**:

Currently, PipeCD has the ability to send deployment notifications to external services like Slack.
Here is how to configure that feature while starting a Piped agent.
https://pipecd.dev/docs/operator-manual/piped/configuring-notifications/

But now it is missing the `WAIT_APPROVAL` event to notify developers that there is a deployment waiting for them to approve.
So it would be nice if we could have it in the near future.

One thing we still don't have a clear path to is how to mention appropriated users in a Slack message because the specified user IDs in `.piped.yaml` are SSO user IDs (like GitHub user ID), not Slack user IDs. So maybe we have to add some additional fields for that connection in Piped configuration.
https://github.com/pipe-cd/examples/blob/master/kubernetes/wait-approval/.pipe.yaml#L11-L14

Some quick paths in the code:
- notification event list https://github.com/pipe-cd/pipe/blob/master/pkg/model/notificationevent.proto#L24-L50
- how to send a notification https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/controller/planner.go#L230-L237
- the package containing wait-approval implementation https://github.com/pipe-cd/pipe/blob/master/pkg/app/piped/executor/waitapproval/waitapproval.go
- notifier package https://github.com/pipe-cd/pipe/tree/master/pkg/app/piped/notifier

**Why is this needed**:

**Comment by nakabonne** [comment]
```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      - name: WAIT_APPROVAL
        with:
          approvers:
            - nghialv
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
  notification:
    mentions:
      - event: WATING_APPROVAL
        slack:
          - nghia
          - nakabonne
        email:
          - nghia@foo.xz
      - event: DEPLOYMENT_STARTED
        slack:
          - nghia
        email:
          - nghia@foo.xz
```

**Comment by nghialv** [comment]
``` yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      - name: WAIT_APPROVAL
        with:
          approvers:
            - nghialv
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:
          - U024BE7LH # nghia
          - U025BE7LK # nakabonne
        email:
          - nghia@foo.xz
      - event: DEPLOYMENT_STARTED
        slack:
          - U024BE7LH # nghia
        email:
          - nghia@foo.xz
```

**Comment by nghialv** [comment]
``` yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      - name: WAIT_APPROVAL
        with:
          approvers:
            - nghialv
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:
          - id: U024BE7LH # nghia
          - id: U025BE7LK # nakabonne
        email:
          - nghia@foo.xz
      - event: DEPLOYMENT_STARTED
        slack:
          - id: U024BE7LH # nghia
        email:
          - nghia@foo.xz
```

**Comment by ono-max** [comment]
``` yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      - name: WAIT_APPROVAL
        with:
          approvers:
            - nghialv
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:
           names:
            - nghia
            - nakabonne
        email:
          - nghia@foo.xz
      - event: DEPLOYMENT_STARTED
        slack:
          - id: U024BE7LH # nghia
        email:
          - nghia@foo.xz
```
