### ISSUE TITLE
Want Event watcher to replace a part of YAML field

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2345]
**What would you like to be added**:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
spec:
  template:
    spec:
      containers:
      - name: helloworld
        image: gcr.io/pipecd/helloworld:{v0.8.0} # <- it's useful if it could replace only v0.8.0
```

**Why is this needed**:
