### ISSUE TITLE
Add text regex support for Event watcher

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2346]
This feature can solve these issues in bulk if all goes well:
- https://github.com/pipe-cd/pipe/issues/2212
- https://github.com/pipe-cd/pipe/issues/2341
- https://github.com/pipe-cd/pipe/issues/2345

### What would you like to be added
I propose adding support for a new configuration field with the name `textField`, which has `regex` and `replacement`.

Event watcher will seek lines that match the given regex. If any matches, it replaces the field with the sent data. `replacement` specifies a replacement value against which a regex replace is performed if the regular expression matches. With it, we can specify which value should be replaced. We can use parenthesized subexpressions (known as capturing groups) in the `regex` field like:

```yaml
apiVersion: pipecd.dev/v1beta1
kind: EventWatcher
spec:
  events:
    - name: update-image
      replacements:
        - file: cloudrun/function.yaml
          textField:
            regex: gcr.io/(.+)/(.+):(.+)
            replacement: $3
        - file: k8s/kustomization.yaml
          yamlField: $.images[0].newTag
```

### Difficulty
- **Performance** - this approach requires performing regex checks for each line. If the target file is a huge one, a significant performance issue can happen.
- **Complexity** - a bit complicated to get familiar with the concept of `regex` and `replacement` for those who have never used Promethues at all, but I feel like it's a quite tiny problem.

### References
- [Prometheus' relabel_confing](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config)
- [The regexp package](https://pkg.go.dev/regexp)

**Comment by nakabonne** [comment]
After careful investigation, it turns out we can't replace the specified capturing group with only `regex` and `replacement`.
I would introduce `lineRegex` and `replaceRegex`. `lineRegex` specifies which line should be updated, and `replaceRegex` specifies which part in the line should be updated.

Let's say for instance, suppose we have such a configuration file and want to update `v0.1.0`, the part of `image: gcr.io/foo/bar:v0.1.0`.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  template:
    spec:
      containers:
      - name: bar
        image: gcr.io/foo/bar:v0.1.0
        ports:
        - containerPort: 9085
        env:
        - name: FOO
          value: {{ .encryptedSecrets.foo }}
```

To do that, we can configure like this:

```yaml
apiVersion: pipecd.dev/v1beta1
kind: EventWatcher
spec:
  events:
    - name: update-image
      replacements:
        - file: cloudrun/function.yaml
          textField:
            # The pattern to detect lines that should be updated by Event watcher.
            lineRegex: "image: gcr.io/foo/bar:(.+)"
            # The pattern to decide which part in the line should be updated.
            replaceRegex: "v[0-9].[0-9].[0-9]"
```

To evaluate the difficulty of this, I opened a PR for that (https://github.com/pipe-cd/pipe/pull/2347). Feel free to look over.

**Comment by nakabonne** [comment]
Alternatively, it could look easier to understand to have one field. The only first capturing group will get replaced.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: EventWatcher
spec:
  events:
    - name: update-image
      replacements:
        - file: cloudrun/function.yaml
          # The only first capturing group enclosed by `()` will be replaced with the new value.
          textField: "image: gcr.io/foo/bar:(v[0-9].[0-9].[0-9])"
```

**Comment by nghialv** [comment]
Yes. The last one looks easier to understand. I'm a little bit concerned about the `textField` name. It would be nice if we could find a better name for it.

**Comment by nakabonne** [comment]
Thank you. I feel you. I honestly would make the name `textRegex` or `targetPattern` or something like that. But to unify the neme convention, I keep the name as-is for now.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: EventWatcher
spec:
  events:
    - name: update-image
      replacements:
        - file: cloudrun/function.yaml
          textField: "image: gcr.io/foo/bar:(v[0-9].[0-9].[0-9])"
        - file: foo/deployment.yaml
          yamlField: $.spec
        - file: bar/deployment.json
          yamlField: $.spec
```

See: https://pipecd.dev/docs/user-guide/configuration-reference/#eventwatcherreplacement
