### ISSUE TITLE
Change Eventwatcher to need to specify repos to be observed

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#2406]
**What would you like to be added**:
Currently, Eventwathcer watches all repos without any settings by default. It can be confusing for those who don't want to use Eventwatcher at all.

So it's great that Eventwatcher requires specifying repos to be observed explicitly. This is a breaking change; we have to mention that on the release note.

```yaml
      # Nothing will happen.
      eventWatcher:
        gitRepos:
```

```yaml
      # Only app-1 will be observed.
      eventWatcher:
        gitRepos:
          - repoId: app-1
            excludes:
              - dev/*.yaml
```

**Why is this needed**:
