### ISSUE TITLE
Add the option to notify all events to users in Slack

### ISSUE THREAD

**Issue by ono-max** [pipe-cd/pipe#2677]
**What would you like to be added**:
Nakao-san said 'The current configuration is a bit difficult to read' as follows:

```YAML
# This deployment has an Approval stage to wait until got
# an approval from one of the specified approvers.
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 10%
      - name: WAIT_APPROVAL
        with:
          approvers:
            - nghialv
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
  notification:
    mentions:
      - event: DEPLOYMENT_WAIT_APPROVAL
        slack:
          - slack-user-id-1  # slack-user-name-1
          - slack-user-id-2  # slack-user-name-2
      # The empty event will notify all events to users.
      - slack:
        - slack-user-id-3  # slack-user-name-3
```

He also suggested us as follows:

```YAML
global[all, common, admin, base, etc]:
  mentions:
    slack:
      - ono-max
    email:
      - ono-max@foo.xz
mentions:
  - event: ""
    slack:
      - ono-max
  - event: "DEPLOYMENT_STARTED"
    slack:
      - nghialv
```

```YAML
- event: "ALL"
    slack:
      - ono-max
  - event: "DEPLOYMENT_STARTED"
    slack:
      - nghialv
```
**Why is this needed**:

**Comment by nghialv** [comment]
IMO, adding another configuration block for that case is a bit overdoing.
Another idea is 

``` yaml
- event: "*"
  slack:
     - ono-max
- event: "DEPLOYMENT_STARTED"
  slack:
     - nghialv
```
