### ISSUE TITLE
Missing "pipecd.dev/variant" label of Kustomize app

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#782]
**What happened**:
I'm running into an issue that the app packaged by Kustomize doesn't come with `pipecd.dev/variant: primary` label.

```
kubectl get po podinfo-fd455bd69-4mz45 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "9797"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-09-10T06:03:11Z"
  generateName: podinfo-fd455bd69-
  labels:
    app: podinfo
    pod-template-hash: fd455bd69
```

That causes being unable to rollout the primary.

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version: v0.6.0
- `control-plane` version: v0.6.0-3-gc071948
- Others:
