### ISSUE TITLE
Unavailable helm install with "--namespace' option

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#789]
**What happened**:
I'm wanting to install an application to `monitoring` namespace, with helm3. For that, I specified `monitoring` as a namespace in the `.pipe.yaml`.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    namespace: monitoring
    helmChart:
      repository: prometheus-community
      name: prometheus
      version: v11.15.0
    helmOptions:
      releaseName: prometheus
      valueFiles:
        - values.yaml
    helmVersion: 3.2.1
```

But it failed. It seems to not use helm's `--namespace` option.

```
Failed to apply manifest: name="prometheus-kube-state-metrics", kind="ServiceAccount", namespace="default", apiVersion="v1" (failed to apply: error: the namespace from the provided object "default" does not match the namespace "monitoring". You must pass '--namespace=default' to perform this operation.  (exit status 1))
```

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version: v0.6.0
- `control-plane` version:
- Others:
