### ISSUE TITLE
Unable to trigger by the dependent directory

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#979]
**What happened**:
Give `foo/` as a dependency directory:
```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  input:
    dependencies:
      - foo/
```
And updated
```diff
❯ g diff 87f24fb 8b06275
diff --git a/foo/foo.yaml b/foo/foo.yaml
index 2bc31e4..20e9ff3 100644
--- a/foo/foo.yaml
+++ b/foo/foo.yaml
@@ -1,2 +1 @@
 foo: bar
-bar: foo
```

But no deployment was triggered.

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:
