### ISSUE TITLE
Unable to prune resources that are no longer defined in Git

### ISSUE THREAD

**Issue by nakabonne** [pipe-cd/pipe#982]
**What happened**:

Enabled auto prune as:

```yaml
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  commitMatcher:
    quickSync: "^Revert"
    pipeline: "^Pipeline"
  sync:
    prune: true
  input:
    namespace: debug
    kubectlVersion: 1.18.5
    dependencies:
      - foo/
  pipeline:
    stages:
      - name: K8S_CANARY_ROLLOUT
        with:
          replicas: 20%
          createService: true
      - name: K8S_PRIMARY_ROLLOUT
      - name: K8S_CANARY_CLEAN
```
And then removed deployment.yaml:

```diff
❯ git diff 4d5cf64 3f1316b
diff --git a/playground/deployment.yaml b/playground/deployment.yaml
deleted file mode 100644
index c08b7e4..0000000
--- a/playground/deployment.yaml
+++ /dev/null
@@ -1,26 +0,0 @@
-apiVersion: apps/v1
-kind: Deployment
-metadata:
-  name: playground
-  labels:
-    app: playground
-spec:
-  replicas: 2
-  revisionHistoryLimit: 2
-  selector:
-    matchLabels:
-      app: playground
-      pipecd.dev/variant: primary
-  template:
-    metadata:
-      labels:
-        app: playground
-        pipecd.dev/variant: primary
-    spec:
-      containers:
-      - name: helloworld
-        image: gcr.io/pipecd/helloworld:v0.7.6-21-g9557a4e
-        args:
-          - server
-        ports:
-        - containerPort: 9085
```

But it has not been removed at all.
```
❯ kubectl get deployments -n debug
NAME         READY   UP-TO-DATE   AVAILABLE   AGE
playground   2/2     2            2           25h
```

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:
